USE WAREHOUSE SF_WH;
USE ROLE DBT_ROLE;
USE SCHEMA SF_FIRE_INCIDENTS.CORE;

SELECT MIN("Incident Date") FROM SF_FIRE_TB;
SELECT MAX("Incident Date") FROM SF_FIRE_TB;
SELECT MAX(DATEDIFF(HOUR, "Arrival DtTm", "Alarm DtTm")) as max_wait_period FROM SF_FIRE_TB;
SELECT MIN(DATEDIFF(MINUTE, "Arrival DtTm", "Alarm DtTm")) as min_wait_period FROM SF_FIRE_TB;

SELECT DISTINCT "Battalion" FROM SF_FIRE_TB;
SELECT DISTINCT "Station Area" FROM SF_FIRE_TB;
SELECT DISTINCT "neighborhood_district" FROM SF_FIRE_TB;

SELECT DISTINCT "Property Use" FROM SF_FIRE_TB;
SELECT DISTINCT "Action Taken Primary" FROM SF_FIRE_TB;
SELECT DISTINCT "Primary Situation" FROM SF_FIRE_TB;

SELECT * FROM SF_FIRE_TB LIMIT 10;
