CREATE OR REPLACE WAREHOUSE SF_WH WITH
  WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 300 
  AUTO_RESUME = TRUE 
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE SF_FIRE_INCIDENTS;

CREATE OR REPLACE SCHEMA CORE;

USE SCHEMA CORE;

CREATE OR REPLACE STORAGE INTEGRATION S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<aws_role_arn>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://rz2-bi/sf_fire_incidents/');

DESC INTEGRATION S3_INTEGRATION;
  
CREATE OR REPLACE STAGE EXTERNAL_STAGE
  URL='s3://rz2-bi/sf_fire_incidents/'
  STORAGE_INTEGRATION = S3_INTEGRATION;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
  ESCAPE = 'NONE'
  ESCAPE_UNENCLOSED_FIELD = '\\'
  DATE_FORMAT = 'YYYY-MM-DDTHH24:MI:SS'
  TIMESTAMP_FORMAT = 'YYYY-MM-DDTHH24:MI:SS'
  NULL_IF = ('\\N');
     
CREATE OR REPLACE TABLE SF_FIRE_TB
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
      INFER_SCHEMA(
        LOCATION=>'@EXTERNAL_STAGE/',
        FILE_FORMAT=>'CSV_FORMAT'
      )
    )
  );

COPY INTO SF_FIRE_TB 
  FROM @EXTERNAL_STAGE
  FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

CREATE OR REPLACE ROLE DBT_ROLE;
GRANT ROLE DBT_ROLE TO USER DROCHA;
GRANT USAGE ON WAREHOUSE SF_WH TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON DATABASE SF_FIRE_INCIDENTS TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA CORE TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA CORE TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON TABLE SF_FIRE_TB TO ROLE DBT_ROLE;
USE ROLE DBT_ROLE;

SELECT * FROM SF_FIRE_TB;
